### ISSUE TITLE
Add Notes and Group Discussion of Ethics in Conclusion

### ISSUE THREAD

**Issue by runderwood** [data-lessons/library-webscraping-DEPRECATED#16]
Provide more information and discussion around the ethics of web scraping, perhaps including pertinent cases studies.

**Comment by vphill** [comment]
A possible example for a group discussion could come from here:

Zimmer, M. (2010). “But the data is already public”: on the ethics of research in Facebook. Ethics and information technology, 12(4), 313-325. - http://www.sfu.ca/~palys/Zimmer-2010-EthicsOfResearchFromFacebook.pdf

Or maybe just additional reading.

**Comment by weaverbel** [comment]
Do you think we need a LOT more than this, @runderwood @ostephens https://github.com/data-lessons/library-webscraping/blob/gh-pages/_episodes/05-conclusion.md ? I think this touches on the main points, i.e. don't be evil, respect copyright etc.

**Comment by vphill** [comment]
@weaverbel I wonder if there is some sort of group discussion, scenario that could be discussed as a group. Just something small that could be engaging to get people to talk/think about the ethics? Might be hoping for too much through.  What do you think?
