### ISSUE TITLE
Lesson maintainers

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/library-webscraping-DEPRECATED#29]
This lesson has no maintainers. Maintainers perform the following tasks:

Maintainers perform a number of important tasks:

- make sure their lesson is consistent with the other Library Carpentry lessons. For example, that the Readme or License pages are correct and consistent (indeed the readme does need a little work https://github.com/data-lessons/library-webscraping/issues/28)
- address any issues that are raised against the lesson
- deal with any pull requests that are made for the lesson.
- after a lesson is taught, make sure that suggestions for improvement from learners and instructors are integrated
- as this is a new lesson, helping it get through the (new) incubator process https://github.com/data-lessons/librarycarpentry/issues/22
- and, ideally, keep up with general Library Carpentry chatter at https://gitter.im/weaverbel/LibraryCarpentry

The lesson needs two maintainers, but more the merrier, especially if we can ensure a good mix of timezones. Anyone up for it?

**Comment by weaverbel** [comment]
I am happy to maintain this one @drjwbaker - at least till we find someone else.

**Comment by drjwbaker** [comment]
Can you ping those who have worked on the lesson to see if anyone want to join you?

**Comment by timtomch** [comment]
Do we still want a 2nd maintainer for this lesson? Given that I've kind of started this mess, I might as well pitch in...

**Comment by drjwbaker** [comment]
If you would @timtomch that would be awesome. Add your name to the README as per template for the other lessons (eg https://github.com/data-lessons/library-shell/blob/gh-pages/README.md)

**Comment by timtomch** [comment]
Done: https://github.com/data-lessons/library-webscraping/pull/35

**Comment by drjwbaker** [comment]
As @weaverbel is do doubt super busy settling into her new job, I'll leave this open as you may want to try and find a 3rd maintainer @timtomch. Obviously - however - do close if you think this will work.
