### ISSUE TITLE
Does this lesson have pre-requisites?

### ISSUE THREAD

**Issue by ostephens** [data-lessons/library-webscraping-DEPRECATED#3]
During review of course assess whether there are any prerequisites, and either make sure these are listed explicitly somewhere, or modify the lesson to avoid the need for pre-requisites

**Comment by weaverbel** [comment]
I definitely want this to be a lesson with no prerequisites @ostephens

**Comment by ostephens** [comment]
So relevant discussion in #7 

Without the lesson being completed following the Sprint discussion hard to be 100% sure, but given the discussion there and the decision to focus on Python & Beautiful Soup I think doing this course this with no previous knowledge of programming would be challenging.

You may be in a better position to comment than me though. I think that it will be simpler than the Scrapy content, but I still don't like the idea of dropping people into Python if they've not seen anything like it before
