### ISSUE TITLE
Talk more about URL hacking

### ISSUE THREAD

**Issue by jnothman** [data-lessons/library-webscraping-DEPRECATED#48]
The structure of a URL is something experienced web scraper builders keep an eye on. It is a basic technique that may deserve discussion in this lesson.

**Comment by deimosnz** [comment]
Perhaps there needs to be a little more brief discussion of the semantic web and some of the underlying data ontologies around linked data? There is a much wider discussion happening in Australia at the government level about adopting a .data.govt.au level ontology that allows for interoperability and standardisation of all govt data. This may be important to web scrapper design going forwards.

**Comment by jnothman** [comment]
I think general data collection and semantic data linking might have to be
another course, or another unit associated with this course. Some concepts
are the same, but ontologies and web scraping (and APIs etc) are a lot to
cover together!
